"""FastAPI mock backend for the MUST dashboard.

Serves the daily exceedance calendar and per-day admin-1 breakdown behind the
calendar-map index. Both endpoints read backend/data/exceedance_calendar.parquet,
which is generated by backend/generate_exceedance_mock.py. Map geometry is read
from the repo-root public/ directory shared with the Next.js app.
"""

import hashlib
import json
import os

import pandas as pd
from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

_BASE_DIR = os.path.dirname(__file__)
_PUBLIC_DIR = os.path.join(_BASE_DIR, "..", "public")

PARQUET_DIR = os.environ.get(
    "PARQUET_DIR",
    os.path.join(_BASE_DIR, "data"),
)
_GEO_DIR = os.path.join(_PUBLIC_DIR, "geo")

app = FastAPI(title="MUST Dashboard API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Daily exceedance calendar, backed by exceedance_calendar.parquet (date x window
# x rp -> p). The per-admin-1 breakdown is synthesised from the day's p plus a
# per-region hash; swapping to live means pointing these endpoints at the real store.
_exceedance_df: pd.DataFrame | None = None
_admin1: list[tuple[str, str]] | None = None


def _get_exceedance_df() -> pd.DataFrame:
    global _exceedance_df
    if _exceedance_df is None:
        path = os.path.join(PARQUET_DIR, "exceedance_calendar.parquet")
        _exceedance_df = pd.read_parquet(path)
    return _exceedance_df


def _get_admin1() -> list[tuple[str, str]]:
    """Admin-1 (GID_1, NAME_1) list, decoded from the storymap geometry."""
    global _admin1
    if _admin1 is None:
        path = os.path.join(_GEO_DIR, "ea-adm1-geo.json")
        with open(path) as fh:
            fc = json.load(fh)
        _admin1 = [(f["properties"]["gid"], f["properties"]["name"]) for f in fc["features"]]
    return _admin1


def _region_p(gid: str, date: str, window: str, rp: str, day_p: float) -> float:
    """Deterministic per-region exceedance, spread around the day's level."""
    h = hashlib.md5(f"{gid}|{date}|{window}|{rp}".encode()).hexdigest()
    frac = int(h[:8], 16) / 0xFFFFFFFF
    return round(min(1.0, day_p * (0.35 + frac * 1.3)), 3)


@app.get("/api/exceedance-calendar")
async def exceedance_calendar(
    window: str = Query("24h"),
    rp: str = Query("10yr"),
    hazard: str = Query("flood"),
):
    df = _get_exceedance_df()
    sel = df[(df["window"] == window) & (df["rp"] == rp)]
    data = [
        {
            "date": row["date"],
            "p": float(row["p"]),
            "members": int(row["members"]),
            "emdat_match": bool(row["emdat_match"]),
        }
        for _, row in sel.iterrows()
    ]
    return {"data": data}


@app.get("/api/exceedance-regions/{date}")
async def exceedance_regions(
    date: str,
    window: str = Query("24h"),
    rp: str = Query("10yr"),
    hazard: str = Query("flood"),
):
    df = _get_exceedance_df()
    row = df[(df["date"] == date) & (df["window"] == window) & (df["rp"] == rp)]
    if len(row) == 0:
        return {"regions": [], "emdat": None}
    day_p = float(row.iloc[0]["p"])
    emdat_match = bool(row.iloc[0]["emdat_match"])

    regions = [
        {
            "shapeID": gid,
            "shapeName": name,
            "p": _region_p(gid, date, window, rp, day_p),
        }
        for gid, name in _get_admin1()
    ]

    emdat = (
        {"event_key": f"{date}-FL", "affected": 46000, "regions": 2, "lead_h": 48}
        if emdat_match
        else None
    )
    return {"regions": regions, "emdat": emdat}


@app.get("/icpac_adm1v3.json")
async def serve_topojson():
    return FileResponse(
        os.path.join(_PUBLIC_DIR, "icpac_adm1v3.json"),
        media_type="application/json",
    )


@app.get("/")
async def root():
    return {
        "status": "ok",
        "message": "MUST Dashboard API (local parquet)",
        "endpoints": [
            "/api/exceedance-calendar?window=24h&rp=10yr&hazard=flood",
            "/api/exceedance-regions/{date}?window=24h&rp=10yr&hazard=flood",
            "/icpac_adm1v3.json",
        ],
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("backend.app:app", host="0.0.0.0", port=8000, reload=True)
